redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Users\\lenovo\\Desktop\\ScholarPro-full-stack\\ScholarPro\\server\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\lenovo\\Desktop\\ScholarPro-full-stack\\ScholarPro\\client\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install --prefix server && npm install --prefix client && npm run build --prefix client"
functions = "C:\\Users\\lenovo\\Desktop\\ScholarPro-full-stack\\ScholarPro\\server\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]