plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\lenovo\\Desktop\\ScholarPro-full-stack\\ScholarPro\\client\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\lenovo\\Desktop\\ScholarPro-full-stack\\ScholarPro\\client"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]